### ISSUE TITLE
Lokaalse installi juhend

### ISSUE THREAD

**Issue by mitselek** [Eesti-Malu-Instituut/we-aruanded#1]
Palun lisage readme'sse ka juhend, kuidas seda oma arvutis installida ja kasutada.
Windowsi platvormist piisab.

**Comment by Konservin** [comment]
README.md loodud, pull request tehtud. Juhend on linuxi platvormile.

**Comment by mitselek** [comment]
Aitäh.

Installeerimisjuhend tundub hea; panen keskkonna lähipäevil püsti.

Nüüd veel kasutusjuhend ka palun - et mis need json failid teevad ja kuidas
neid hallata. See osa võiks olla võimalikult mittetehniline, põhirõhuga
loogikale. Varustatud näidete ja selgitustega.



Mihkel Putrinš +372 5656 0978

**Comment by mitselek** [comment]
Ma paluksin siiski ssh ühendust võtme, mitte parooliga. Võibolla jäi mul
see soov täpselt väljendamata.

mihkel
5656 0978

**Comment by mitselek** [comment]
- [x] Juhendist on puudu PHP installeerimise käsk,
- [ ] Nõuded süsteemile peatükis pole mainitud ssh2 moodulit
