### ISSUE TITLE
Valed andmebaasi nimed

### ISSUE THREAD

**Issue by mitselek** [Eesti-Malu-Instituut/we-aruanded#8]
https://github.com/Eesti-Malu-Instituut/we-aruanded/blob/3d7bee6c561adf6fffbe4c3cea8009a50b8aaa80/filters.json#L87

Meie jagatud andmebaasi dumpis olid tabelid eraldi baasides - teil läks arenduse käigus struktuur sassi ja praegu tänu sellele päringud õigetesse baasidesse ei saa jõuda.

**Comment by Konservin** [comment]
Lisasin filter.json tabelisse õigete baaside nimed.

**Comment by mitselek** [comment]
![image](https://github.com/Eesti-Malu-Instituut/we-aruanded/assets/873710/700e1306-1ed2-4cb6-abe1-8fefac89c4e6)
